#:schema node_modules/wrangler/config-schema.json
name = "cratedig"
main = "router.ts"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "Text"
globs = ["**/*.pug"]
fallthrough = false

# https://developers.cloudflare.com/workers/observability/logs/workers-logs/
[observability]
enabled = true

# D1: https://developers.cloudflare.com/d1/
[[d1_databases]]
binding = "DB"
database_name = "vinyl-db"
database_id = "931bf6dc-4e8c-4b64-912d-ec1c4403ca28"

# R2: https://developers.cloudflare.com/r2/
# [[r2_buckets]]
# binding = "COVERART"
# bucket_name = "cover-art"

# Vectorize: https://developers.cloudflare.com/vectorize
# [[vectorize]]
# binding = "VECTORS"
# index_name = "media-index"
